apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: revenda-veiculos
data:
  SPRING_PROFILES_ACTIVE: "kubernetes"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/revenda_veiculos?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "false"
  SERVER_PORT: "8080"
  LOGGING_LEVEL_ORG_COM: "INFO"
  LOGGING_CONFIG: "classpath:logback-kubernetes.xml"
  db.host: "mysql-service"
  db.port: "3306"
  db.name: "revenda_veiculos"
  app.name: "revenda-veiculos"
