apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: revenda-veiculos
type: Opaque
data:
  # root (base64: cm9vdA==)
  db.username: cm9vdA==
  # root (base64: cm9vdA==)
  db.password: cm9vdA==
